// Code generated by mockery v2.8.0. DO NOT EDIT.

package services

import (
	context "context"

	domain "com.t-systems-mms.cwa/domain"
	mock "github.com/stretchr/testify/mock"
)

// Operators is an autogenerated mock type for the Operators type
type Operators struct {
	mock.Mock
}

// GetCurrentOperator provides a mock function with given fields: ctx
func (_m *Operators) GetCurrentOperator(ctx context.Context) (domain.Operator, error) {
	ret := _m.Called(ctx)

	var r0 domain.Operator
	if rf, ok := ret.Get(0).(func(context.Context) domain.Operator); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Operator)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
